### ISSUE TITLE
Fails on SSE4 CPU

### ISSUE THREAD

**Issue by COhsrt** [PoC-Consortium/scavenger#1]
Scavenger fails with SSE4 CPU

Output of the "optimized build"
```
/sources/scavenger/target/release$ ./scavenger
using sse2
Ungültiger Maschinenbefehl
```
Machine/OS Details
```
$ grep -E "^(model name|flags)" /proc/cpuinfo |head -2
model name      : Intel(R) Atom(TM) CPU  C2550  @ 2.40GHz
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 movbe popcnt tsc_deadline_timer aes rdrand lahf_lm 3dnowprefetch epb tpr_shadow vnmi flexpriority ept vpid tsc_adjust smep erms dtherm ida arat
$ uname -a
Linux server05 4.9.0-7-amd64 #1 SMP Debian 4.9.110-1 (2018-07-05) x86_64 GNU/Linux
$ cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-4.9.0-7-amd64 root=UUID=bc8176bb-2357-4b3f-a117-ba1e49dc1c3c ro quiet pti=off
$ cat /etc/debian_version
9.5
$ uptime
 23:15:30 up 4 days,  2:44,  2 users,  load average: 5,83, 5,51, 4,11

```
Build log
```
$ cargo build --release
   Compiling nodrop v0.1.12
   Compiling libc v0.2.42
   Compiling cfg-if v0.1.3
   Compiling num-traits v0.2.5
   Compiling memoffset v0.2.1
   Compiling byteorder v1.2.3
   Compiling lazy_static v1.0.1
   Compiling num-integer v0.1.39
   Compiling scopeguard v0.3.3
   Compiling lazycell v0.6.0
   Compiling slab v0.4.0
   Compiling futures v0.1.23
   Compiling num-iter v0.1.37
   Compiling unicode-xid v0.1.0
   Compiling rustc-serialize v0.3.24
   Compiling serde v1.0.65
   Compiling cc v1.0.18
   Compiling fnv v1.0.6
   Compiling matches v0.1.6
   Compiling rayon-core v1.4.1
   Compiling itoa v0.4.1
   Compiling try-lock v0.2.2
   Compiling indexmap v1.0.1
   Compiling unicode-normalization v0.1.7
   Compiling linked-hash-map v0.5.1
   Compiling string v0.1.0
   Compiling rayon v1.0.2
   Compiling httparse v1.2.4
   Compiling dtoa v0.4.2
   Compiling scoped-tls v0.1.2
   Compiling either v1.5.0
   Compiling percent-encoding v1.0.1
   Compiling libc v0.1.12
   Compiling hex v0.3.2
   Compiling crossbeam-utils v0.3.2
   Compiling log v0.4.1
   Compiling crossbeam-utils v0.2.2
   Compiling arrayvec v0.4.7
   Compiling iovec v0.1.2
   Compiling net2 v0.2.32
   Compiling rand v0.4.2
   Compiling num_cpus v1.8.0
   Compiling time v0.1.40
   Compiling filetime v0.2.1
   Compiling num_cpus v0.2.13
   Compiling proc-macro2 v0.4.5
   Compiling unicode-bidi v0.3.4
   Compiling tokio-executor v0.1.2
   Compiling sys-info v0.5.6
   Compiling scavenger v1.0.0-beta (file:///home/fawkes/sources/scavenger)
   Compiling yaml-rust v0.4.0
   Compiling want v0.0.5
   Compiling bytes v0.4.8
   Compiling crossbeam-epoch v0.4.1
   Compiling crossbeam-epoch v0.3.1
   Compiling mio v0.6.14
   Compiling futures-cpupool v0.1.8
   Compiling rand v0.3.22
   Compiling tokio-timer v0.2.4
   Compiling quote v0.6.3
   Compiling tokio-io v0.1.6
   Compiling http v0.1.7
   Compiling num-complex v0.1.43
   Compiling idna v0.1.5
   Compiling crossbeam-deque v0.2.0
   Compiling crossbeam-deque v0.3.1
   Compiling chan v0.1.21
   Compiling syn v0.14.2
warning: src/c/mshabal_128.c: In function ‘simd128_mshabal_close’:
warning: src/c/mshabal_128.c:317:13: warning: unused parameter ‘ub0’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:              ^~~
warning: src/c/mshabal_128.c:317:27: warning: unused parameter ‘ub1’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                            ^~~
warning: src/c/mshabal_128.c:317:41: warning: unused parameter ‘ub2’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                                          ^~~
warning: src/c/mshabal_128.c:317:55: warning: unused parameter ‘ub3’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                                                        ^~~
warning: src/c/mshabal_128.c:317:69: warning: unused parameter ‘n’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                                                                      ^
warning: src/c/mshabal_128.c: In function ‘simd128_mshabal_openclose_fast’:
warning: src/c/mshabal_128.c:650:14: warning: unused parameter ‘n’ [-Wunused-parameter]
warning:      unsigned n)
warning:               ^
warning: src/c/mshabal_256.c: In function ‘simd256_mshabal_close’:
warning: src/c/mshabal_256.c:365:14: warning: unused parameter ‘ub0’ [-Wunused-parameter]
warning:      unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3,
warning:               ^~~
warning: src/c/mshabal_256.c:365:28: warning: unused parameter ‘ub1’ [-Wunused-parameter]
warning:      unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3,
warning:                             ^~~
warning: src/c/mshabal_256.c:365:42: warning: unused parameter ‘ub2’ [-Wunused-parameter]
warning:      unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3,
warning:                                           ^~~
warning: src/c/mshabal_256.c:365:56: warning: unused parameter ‘ub3’ [-Wunused-parameter]
warning:      unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3,
warning:                                                         ^~~
warning: src/c/mshabal_256.c:366:14: warning: unused parameter ‘ub4’ [-Wunused-parameter]
warning:      unsigned ub4, unsigned ub5, unsigned ub6, unsigned ub7,
warning:               ^~~
warning: src/c/mshabal_256.c:366:28: warning: unused parameter ‘ub5’ [-Wunused-parameter]
warning:      unsigned ub4, unsigned ub5, unsigned ub6, unsigned ub7,
warning:                             ^~~
warning: src/c/mshabal_256.c:366:42: warning: unused parameter ‘ub6’ [-Wunused-parameter]
warning:      unsigned ub4, unsigned ub5, unsigned ub6, unsigned ub7,
warning:                                           ^~~
warning: src/c/mshabal_256.c:366:56: warning: unused parameter ‘ub7’ [-Wunused-parameter]
warning:      unsigned ub4, unsigned ub5, unsigned ub6, unsigned ub7,
warning:                                                         ^~~
warning: src/c/mshabal_256.c:367:14: warning: unused parameter ‘n’ [-Wunused-parameter]
warning:      unsigned n,
warning:               ^
warning: src/c/mshabal_256.c: In function ‘simd256_mshabal_openclose_fast’:
warning: src/c/mshabal_256.c:715:14: warning: unused parameter ‘n’ [-Wunused-parameter]
warning:      unsigned n)
warning:               ^
warning: src/c/shabal.c: In function ‘find_best_deadline_sse2’:
warning: src/c/shabal.c:127:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d0 = *((uint64_t *) res0);
warning:      ^~
warning: src/c/shabal.c:128:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d1 = *((uint64_t *) res1);
warning:      ^~
warning: src/c/shabal.c:129:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d2 = *((uint64_t *) res2);
warning:      ^~
warning: src/c/shabal.c:130:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d3 = *((uint64_t *) res3);
warning:      ^~
warning: src/c/shabal.c: In function ‘find_best_deadline_avx’:
warning: src/c/shabal.c:190:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d0 = *((uint64_t *) res0);
warning:      ^~
warning: src/c/shabal.c:191:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d1 = *((uint64_t *) res1);
warning:      ^~
warning: src/c/shabal.c:192:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d2 = *((uint64_t *) res2);
warning:      ^~
warning: src/c/shabal.c:193:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d3 = *((uint64_t *) res3);
warning:      ^~
warning: src/c/shabal.c: In function ‘find_best_deadline_avx2’:
warning: src/c/shabal.c:271:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d0 = *((uint64_t *) res0);
warning:      ^~
warning: src/c/shabal.c:272:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d1 = *((uint64_t *) res1);
warning:      ^~
warning: src/c/shabal.c:273:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d2 = *((uint64_t *) res2);
warning:      ^~
warning: src/c/shabal.c:274:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d3 = *((uint64_t *) res3);
warning:      ^~
warning: src/c/shabal.c:275:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d4 = *((uint64_t *) res4);
warning:      ^~
warning: src/c/shabal.c:276:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d5 = *((uint64_t *) res5);
warning:      ^~
warning: src/c/shabal.c:277:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d6 = *((uint64_t *) res6);
warning:      ^~
warning: src/c/shabal.c:278:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d7 = *((uint64_t *) res7);
warning:      ^~
   Compiling tokio-reactor v0.1.1
   Compiling num-bigint v0.1.44
   Compiling tokio-threadpool v0.1.5
   Compiling h2 v0.1.10
   Compiling serde_yaml v0.7.4
   Compiling serde_json v1.0.19
   Compiling tokio-udp v0.1.0
   Compiling tokio-tcp v0.1.0
   Compiling num-rational v0.1.42
   Compiling url v1.7.1
   Compiling tokio-fs v0.1.0
   Compiling serde_derive v1.0.65
   Compiling tokio v0.1.7
   Compiling num v0.1.42
   Compiling stopwatch v0.0.7
   Compiling hyper v0.12.5
   Compiling tokio-core v0.1.17
    Finished release [optimized] target(s) in 7m 06s
```

Too bad it doesn't work on a CPU without AVX, but it was worth a try. Maybe you can find a fix. Feel free to contact me using discord @Kalinka

**Comment by spebern** [comment]
Hi,
try edit the build.rs file and add a -O2 flag

**Comment by COhsrt** [comment]
Nope, doesn't change anything - If I did it the right way?

```
$ cargo build --release
   Compiling scavenger v1.0.0-beta (file:///home/fawkes/sources/scavenger)
warning: src/c/mshabal_128.c: In function ‘simd128_mshabal_close’:
warning: src/c/mshabal_128.c:317:13: warning: unused parameter ‘ub0’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:              ^~~
warning: src/c/mshabal_128.c:317:27: warning: unused parameter ‘ub1’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                            ^~~
warning: src/c/mshabal_128.c:317:41: warning: unused parameter ‘ub2’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                                          ^~~
warning: src/c/mshabal_128.c:317:55: warning: unused parameter ‘ub3’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                                                        ^~~
warning: src/c/mshabal_128.c:317:69: warning: unused parameter ‘n’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                                                                      ^
warning: src/c/mshabal_128.c: In function ‘simd128_mshabal_openclose_fast’:
warning: src/c/mshabal_128.c:650:14: warning: unused parameter ‘n’ [-Wunused-parameter]
warning:      unsigned n)
warning:               ^
warning: src/c/mshabal_256.c: In function ‘simd256_mshabal_close’:
warning: src/c/mshabal_256.c:365:14: warning: unused parameter ‘ub0’ [-Wunused-parameter]
warning:      unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3,
warning:               ^~~
warning: src/c/mshabal_256.c:365:28: warning: unused parameter ‘ub1’ [-Wunused-parameter]
warning:      unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3,
warning:                             ^~~
warning: src/c/mshabal_256.c:365:42: warning: unused parameter ‘ub2’ [-Wunused-parameter]
warning:      unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3,
warning:                                           ^~~
warning: src/c/mshabal_256.c:365:56: warning: unused parameter ‘ub3’ [-Wunused-parameter]
warning:      unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3,
warning:                                                         ^~~
warning: src/c/mshabal_256.c:366:14: warning: unused parameter ‘ub4’ [-Wunused-parameter]
warning:      unsigned ub4, unsigned ub5, unsigned ub6, unsigned ub7,
warning:               ^~~
warning: src/c/mshabal_256.c:366:28: warning: unused parameter ‘ub5’ [-Wunused-parameter]
warning:      unsigned ub4, unsigned ub5, unsigned ub6, unsigned ub7,
warning:                             ^~~
warning: src/c/mshabal_256.c:366:42: warning: unused parameter ‘ub6’ [-Wunused-parameter]
warning:      unsigned ub4, unsigned ub5, unsigned ub6, unsigned ub7,
warning:                                           ^~~
warning: src/c/mshabal_256.c:366:56: warning: unused parameter ‘ub7’ [-Wunused-parameter]
warning:      unsigned ub4, unsigned ub5, unsigned ub6, unsigned ub7,
warning:                                                         ^~~
warning: src/c/mshabal_256.c:367:14: warning: unused parameter ‘n’ [-Wunused-parameter]
warning:      unsigned n,
warning:               ^
warning: src/c/mshabal_256.c: In function ‘simd256_mshabal_openclose_fast’:
warning: src/c/mshabal_256.c:715:14: warning: unused parameter ‘n’ [-Wunused-parameter]
warning:      unsigned n)
warning:               ^
warning: src/c/shabal.c: In function ‘find_best_deadline_sse2’:
warning: src/c/shabal.c:127:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d0 = *((uint64_t *) res0);
warning:      ^~
warning: src/c/shabal.c:128:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d1 = *((uint64_t *) res1);
warning:      ^~
warning: src/c/shabal.c:129:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d2 = *((uint64_t *) res2);
warning:      ^~
warning: src/c/shabal.c:130:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d3 = *((uint64_t *) res3);
warning:      ^~
warning: src/c/shabal.c: In function ‘find_best_deadline_avx’:
warning: src/c/shabal.c:190:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d0 = *((uint64_t *) res0);
warning:      ^~
warning: src/c/shabal.c:191:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d1 = *((uint64_t *) res1);
warning:      ^~
warning: src/c/shabal.c:192:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d2 = *((uint64_t *) res2);
warning:      ^~
warning: src/c/shabal.c:193:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d3 = *((uint64_t *) res3);
warning:      ^~
warning: src/c/shabal.c: In function ‘find_best_deadline_avx2’:
warning: src/c/shabal.c:271:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d0 = *((uint64_t *) res0);
warning:      ^~
warning: src/c/shabal.c:272:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d1 = *((uint64_t *) res1);
warning:      ^~
warning: src/c/shabal.c:273:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d2 = *((uint64_t *) res2);
warning:      ^~
warning: src/c/shabal.c:274:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d3 = *((uint64_t *) res3);
warning:      ^~
warning: src/c/shabal.c:275:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d4 = *((uint64_t *) res4);
warning:      ^~
warning: src/c/shabal.c:276:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d5 = *((uint64_t *) res5);
warning:      ^~
warning: src/c/shabal.c:277:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d6 = *((uint64_t *) res6);
warning:      ^~
warning: src/c/shabal.c:278:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
warning:      d7 = *((uint64_t *) res7);
warning:      ^~
    Finished release [optimized] target(s) in 1m 08s
$ ./target/release/scavenger
using sse2
Ungültiger Maschinenbefehl
$ cat build.rs
extern crate cc;

fn main() {
    cc::Build::new()
        .file("src/c/shabal64.s")
        .file("src/c/mshabal_128.c")
        .file("src/c/mshabal_256.c")
        .file("src/c/shabal.c")
        .flag("-mavx2")
        .flag("-O2")
        .flag("-std=c99")
        .compile("libshabal.a");
}

```

**Comment by JohnnyFFM** [comment]
What happens if you replace -mavx2 with -msse2 in build.rs?

**Comment by JohnnyFFM** [comment]
This should fix it, please add -march=native and let us know.

**Comment by COhsrt** [comment]
Sorry but it didn't fix it :-(

```
$ git pull
Aktualisiere d2fa3b1..3b34af5
Fast-forward
 Cargo.lock              |  109 +++++++++++++
 Cargo.toml              |    4 +-
 README.md               |   30 +++-
 build.rs                |   15 +-
 config.yaml             |    2 +
 src/c/shabal64-darwin.s | 1729 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/config.rs           |   23 ++-
 src/main.rs             |   21 ++-
 src/miner.rs            |   42 ++++-
 src/plot.rs             |   87 ++++++++++-
 src/reader.rs           |   67 ++++----
 src/requests.rs         |   69 +++++++--
 src/utils.rs            |   46 ++++++
 src/worker.rs           |    5 +
 14 files changed, 2179 insertions(+), 70 deletions(-)
 create mode 100644 src/c/shabal64-darwin.s
```


```
$ cargo run
 Downloading rand v0.5.4
 Downloading atty v0.2.11
 Downloading rand_core v0.2.1
   Compiling unicode-width v0.1.5
   Compiling bitflags v1.0.3
   Compiling rand_core v0.2.1
   Compiling strsim v0.7.0
   Compiling vec_map v0.8.1
   Compiling ansi_term v0.10.2
   Compiling atty v0.2.11
   Compiling scavenger v1.0.0-beta (file:///home/fawkes/sources/scavenger)
   Compiling textwrap v0.9.0
   Compiling rand v0.5.4
   Compiling clap v2.30.0
warning: src/c/mshabal_128.c: In function ‘simd128_mshabal_close’:
warning: src/c/mshabal_128.c:317:13: warning: unused parameter ‘ub0’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:              ^~~
warning: src/c/mshabal_128.c:317:27: warning: unused parameter ‘ub1’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                            ^~~
warning: src/c/mshabal_128.c:317:41: warning: unused parameter ‘ub2’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                                          ^~~
warning: src/c/mshabal_128.c:317:55: warning: unused parameter ‘ub3’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                                                        ^~~
warning: src/c/mshabal_128.c:317:69: warning: unused parameter ‘n’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                                                                      ^
warning: src/c/mshabal_128.c: In function ‘simd128_mshabal_openclose_fast’:
warning: src/c/mshabal_128.c:650:14: warning: unused parameter ‘n’ [-Wunused-parameter]
warning:      unsigned n)
warning:               ^
warning: src/c/mshabal_256.c: In function ‘simd256_mshabal_close’:
warning: src/c/mshabal_256.c:365:14: warning: unused parameter ‘ub0’ [-Wunused-parameter]
warning:      unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3,
warning:               ^~~
warning: src/c/mshabal_256.c:365:28: warning: unused parameter ‘ub1’ [-Wunused-parameter]
warning:      unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3,
warning:                             ^~~
warning: src/c/mshabal_256.c:365:42: warning: unused parameter ‘ub2’ [-Wunused-parameter]
warning:      unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3,
warning:                                           ^~~
warning: src/c/mshabal_256.c:365:56: warning: unused parameter ‘ub3’ [-Wunused-parameter]
warning:      unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3,
warning:                                                         ^~~
warning: src/c/mshabal_256.c:366:14: warning: unused parameter ‘ub4’ [-Wunused-parameter]
warning:      unsigned ub4, unsigned ub5, unsigned ub6, unsigned ub7,
warning:               ^~~
warning: src/c/mshabal_256.c:366:28: warning: unused parameter ‘ub5’ [-Wunused-parameter]
warning:      unsigned ub4, unsigned ub5, unsigned ub6, unsigned ub7,
warning:                             ^~~
warning: src/c/mshabal_256.c:366:42: warning: unused parameter ‘ub6’ [-Wunused-parameter]
warning:      unsigned ub4, unsigned ub5, unsigned ub6, unsigned ub7,
warning:                                           ^~~
warning: src/c/mshabal_256.c:366:56: warning: unused parameter ‘ub7’ [-Wunused-parameter]
warning:      unsigned ub4, unsigned ub5, unsigned ub6, unsigned ub7,
warning:                                                         ^~~
warning: src/c/mshabal_256.c:367:14: warning: unused parameter ‘n’ [-Wunused-parameter]
warning:      unsigned n,
warning:               ^
warning: src/c/mshabal_256.c: In function ‘simd256_mshabal_openclose_fast’:
warning: src/c/mshabal_256.c:715:14: warning: unused parameter ‘n’ [-Wunused-parameter]
warning:      unsigned n)
warning:               ^
    Finished dev [unoptimized + debuginfo] target(s) in 1m 03s
     Running `target/debug/scavenger`
using sse2
Ungültiger Maschinenbefehl
```

Build.rs info (I added -msse2 aswell, doesnt change anything)
```
$ cat build.rs
extern crate cc;
use std::env;

fn main() {
    let target_os = env::var("CARGO_CFG_TARGET_OS");

    let mut config = cc::Build::new();

    if target_os == Ok("macos".to_string()) {
        config.file("src/c/shabal64-darwin.s");
    } else {
        config.file("src/c/shabal64.s");
    }

    config
        .file("src/c/mshabal_128.c")
        .file("src/c/mshabal_256.c")
        .file("src/c/shabal.c")
        .flag("-mavx2")
        .flag("-std=c99")
        .flag("-march=native")
        .compile("libshabal.a");
}
```

**Comment by COhsrt** [comment]
Update:

as the current readme suggests "-O2" ... this doesn't work either, same output.

**Comment by JohnnyFFM** [comment]
can you let me know what Cpu you have?

**Comment by COhsrt** [comment]
See Machine/OS Details in initial post. 

```
$ grep -E "^(model name|flags)" /proc/cpuinfo |head -2
model name      : Intel(R) Atom(TM) CPU  C2550  @ 2.40GHz
```

**Comment by COhsrt** [comment]
Actually even this doesn't work.

tried:
-march=silvermont -O2
-march=silvermont
-march=atom -O2
-march=atom

gcc version:
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)
```

**Comment by mmullis** [comment]
Sorry I don't have a patch for you but wanted to share what i found before anyone spends more time on this. Perhaps try same solution on atom before coming up with a permanent approach.

I had the same problem on a G4560 (pentium quad).  It has sse2/3/4.1/4.2 support but no avx.
The failure is on the first call to _mm_loadu_si128.
The avx/2 related functions and -mavx2 flag are not benign in this situation.
It clobbers something and causes "Illegal Instruction" failures on the sse2 path.

In my case, the following worked enough to get past the Illegal Instruction problem.
1. Remove the -mavx2 flag 
2. Block off the avx calls with following
```
#ifdef __AVX2__
// the current avx functions
#else
// stubs to do nothing or print invalid call if AVX2 is not implemented would be good
#endif
```

**Comment by JohnnyFFM** [comment]
Interesting.. the mentioned call is a sse2 call, but it seems like it might trigger avx code in certain circumstances. Have to dig into this... I read about another way blocking avx calls by just adding the flag -mno-avx. Would be cool if someone could test it.

**Comment by madf0x** [comment]
I have just tried to compile this on an atom board and had the same issues, tried all the variations of flags, nothing worked. I'll give -mno-avx a last try, after that i'll give up until stable :-) 
Thanks for all your effort on this.

**Comment by COhsrt** [comment]
As we've been talking about this yesterday - the c-version of the shabal implementation doesnt work actually :-(
checking out the latest master
```
$ git pull
remote: Counting objects: 32, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 32 (delta 23), reused 25 (delta 16), pack-reused 0
Entpacke Objekte: 100% (32/32), Fertig.
Von https://github.com/PoC-Consortium/scavenger
   6807d25..03ffff0  master         -> origin/master
   177dc83..e9b7366  output-logging -> origin/output-logging
Aktualisiere 6807d25..03ffff0
Fast-forward
 build.rs                |   16 +--
 src/c/shabal64-darwin.s | 1729 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 src/c/shabal64.s        | 1729 --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 src/c/sph_shabal.c      |  548 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/c/sph_shabal.h      |  124 ++++++++++++++++++
 src/c/sph_types.h       | 1976 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/shabals.rs          |   12 +-
 7 files changed, 2659 insertions(+), 3475 deletions(-)
 delete mode 100644 src/c/shabal64-darwin.s
 delete mode 100644 src/c/shabal64.s
 create mode 100644 src/c/sph_shabal.c
 create mode 100644 src/c/sph_shabal.h
 create mode 100644 src/c/sph_types.h
```
compile output
```
$ cargo run
   Compiling scavenger v1.0.0-beta (file:///home/fawkes/sources/scavenger)
warning: src/c/mshabal_128.c: In function ‘simd128_mshabal_close’:
warning: src/c/mshabal_128.c:317:13: warning: unused parameter ‘ub0’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:              ^~~
warning: src/c/mshabal_128.c:317:27: warning: unused parameter ‘ub1’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                            ^~~
warning: src/c/mshabal_128.c:317:41: warning: unused parameter ‘ub2’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                                          ^~~
warning: src/c/mshabal_128.c:317:55: warning: unused parameter ‘ub3’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                                                        ^~~
warning: src/c/mshabal_128.c:317:69: warning: unused parameter ‘n’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                                                                      ^
warning: src/c/mshabal_128.c: In function ‘simd128_mshabal_openclose_fast’:
warning: src/c/mshabal_128.c:650:14: warning: unused parameter ‘n’ [-Wunused-parameter]
warning:      unsigned n)
warning:               ^
warning: src/c/mshabal_256.c: In function ‘simd256_mshabal_close’:
warning: src/c/mshabal_256.c:365:14: warning: unused parameter ‘ub0’ [-Wunused-parameter]
warning:      unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3,
warning:               ^~~
warning: src/c/mshabal_256.c:365:28: warning: unused parameter ‘ub1’ [-Wunused-parameter]
warning:      unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3,
warning:                             ^~~
warning: src/c/mshabal_256.c:365:42: warning: unused parameter ‘ub2’ [-Wunused-parameter]
warning:      unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3,
warning:                                           ^~~
warning: src/c/mshabal_256.c:365:56: warning: unused parameter ‘ub3’ [-Wunused-parameter]
warning:      unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3,
warning:                                                         ^~~
warning: src/c/mshabal_256.c:366:14: warning: unused parameter ‘ub4’ [-Wunused-parameter]
warning:      unsigned ub4, unsigned ub5, unsigned ub6, unsigned ub7,
warning:               ^~~
warning: src/c/mshabal_256.c:366:28: warning: unused parameter ‘ub5’ [-Wunused-parameter]
warning:      unsigned ub4, unsigned ub5, unsigned ub6, unsigned ub7,
warning:                             ^~~
warning: src/c/mshabal_256.c:366:42: warning: unused parameter ‘ub6’ [-Wunused-parameter]
warning:      unsigned ub4, unsigned ub5, unsigned ub6, unsigned ub7,
warning:                                           ^~~
warning: src/c/mshabal_256.c:366:56: warning: unused parameter ‘ub7’ [-Wunused-parameter]
warning:      unsigned ub4, unsigned ub5, unsigned ub6, unsigned ub7,
warning:                                                         ^~~
warning: src/c/mshabal_256.c:367:14: warning: unused parameter ‘n’ [-Wunused-parameter]
warning:      unsigned n,
warning:               ^
warning: src/c/mshabal_256.c: In function ‘simd256_mshabal_openclose_fast’:
warning: src/c/mshabal_256.c:715:14: warning: unused parameter ‘n’ [-Wunused-parameter]
warning:      unsigned n)
warning:               ^
    Finished dev [unoptimized + debuginfo] target(s) in 17.81s
     Running `target/debug/scavenger`
using sse2
Ungültiger Maschinenbefehl
```

current build.rs
```
$ cat build.rs
extern crate cc;

fn main() {
    let mut config = cc::Build::new();

    #[cfg(target_env = "msvc")]
    config.flag("/arch:AVX2");
    #[cfg(not(target_env = "msvc"))]
    config.flag("-mavx2").flag("-std=c99").flag("-march=native");

    config
        .file("src/c/sph_shabal.c")
        .file("src/c/mshabal_128.c")
        .file("src/c/mshabal_256.c")
        .file("src/c/shabal.c")
        .compile("libshabal.a");
}
```

**Comment by mmullis** [comment]
I created an experimental branch which does something different from my prior post to separate sse2 from avx/2. (see pull #11)
I split the code up a little and changed build.rs to pick what to compile. 
Not sure if the -m flags matter at all now with this approach.

build.rs should select to compile avx/2 code if avx is present and if not, just the sse2 code.
Tested the avx path on mac- compiles and runs (until it hits the lsblk call issue).

**Comment by COhsrt** [comment]
That works!

```
$ cargo run
 Downloading log4rs v0.8.0
 Downloading chrono v0.4.5
 Downloading log v0.4.3
 Downloading humantime v1.1.1
 Downloading typemap v0.3.3
 Downloading flate2 v1.0.2
 Downloading antidote v1.0.0
 Downloading crossbeam v0.3.2
 Downloading serde-value v0.5.2
 Downloading log-mdc v0.1.0
 Downloading quick-error v1.2.2
 Downloading unsafe-any v0.4.2
 Downloading traitobject v0.1.0
 Downloading miniz-sys v0.1.10
 Downloading ordered-float v0.5.0
 Downloading unreachable v0.1.1
 Downloading num-traits v0.1.43
 Downloading void v1.0.2
   Compiling serde v1.0.65
   Compiling nodrop v0.1.12
   Compiling cfg-if v0.1.3
   Compiling libc v0.2.42
   Compiling num-traits v0.2.5
   Compiling num-integer v0.1.39
   Compiling byteorder v1.2.3
   Compiling lazy_static v1.0.1
   Compiling memoffset v0.2.1
   Compiling scopeguard v0.3.3
   Compiling lazycell v0.6.0
   Compiling cc v1.0.18
   Compiling unicode-xid v0.1.0
   Compiling slab v0.4.0
   Compiling futures v0.1.23
   Compiling void v1.0.2
   Compiling rustc-serialize v0.3.24
   Compiling num-iter v0.1.37
   Compiling linked-hash-map v0.5.1
   Compiling matches v0.1.6
   Compiling traitobject v0.1.0
   Compiling itoa v0.4.1
   Compiling rayon-core v1.4.1
   Compiling fnv v1.0.6
   Compiling try-lock v0.2.2
   Compiling dtoa v0.4.2
   Compiling quick-error v1.2.2
   Compiling rayon v1.0.2
   Compiling unicode-normalization v0.1.7
   Compiling unicode-width v0.1.5
   Compiling indexmap v1.0.1
   Compiling string v0.1.0
   Compiling ansi_term v0.10.2
   Compiling rand_core v0.2.1
   Compiling vec_map v0.8.1
   Compiling either v1.5.0
   Compiling crossbeam v0.3.2
   Compiling percent-encoding v1.0.1
   Compiling bitflags v1.0.3
   Compiling log-mdc v0.1.0
   Compiling scoped-tls v0.1.2
   Compiling antidote v1.0.0
   Compiling strsim v0.7.0
   Compiling httparse v1.2.4
   Compiling libc v0.1.12
   Compiling hex v0.3.2
   Compiling crossbeam-utils v0.3.2
   Compiling crossbeam-utils v0.2.2
   Compiling arrayvec v0.4.7
   Compiling proc-macro2 v0.4.5
   Compiling iovec v0.1.2
   Compiling net2 v0.2.32
   Compiling rand v0.4.2
   Compiling num_cpus v1.8.0
   Compiling time v0.1.40
   Compiling atty v0.2.11
   Compiling num_cpus v0.2.13
   Compiling filetime v0.2.1
   Compiling unreachable v0.1.1
   Compiling miniz-sys v0.1.10
   Compiling sys-info v0.5.6
   Compiling scavenger v1.0.0-beta (file:///home/fawkes/sources/forks/scavenger)
   Compiling unicode-bidi v0.3.4
   Compiling unsafe-any v0.4.2
   Compiling yaml-rust v0.4.0
   Compiling humantime v1.1.1
   Compiling textwrap v0.9.0
   Compiling tokio-executor v0.1.2
   Compiling rand v0.5.4
   Compiling crossbeam-epoch v0.4.1
   Compiling crossbeam-epoch v0.3.1
   Compiling bytes v0.4.8
   Compiling quote v0.6.3
   Compiling futures-cpupool v0.1.8
   Compiling rand v0.3.22
   Compiling typemap v0.3.3
   Compiling clap v2.30.0
   Compiling tokio-timer v0.2.4
   Compiling num-traits v0.1.43
   Compiling num-complex v0.1.43
   Compiling crossbeam-deque v0.2.0
   Compiling crossbeam-deque v0.3.1
   Compiling syn v0.14.2
   Compiling http v0.1.7
   Compiling chan v0.1.21
   Compiling idna v0.1.5
   Compiling ordered-float v0.5.0
warning: src/c/mshabal_128.c: In function ‘simd128_mshabal_close’:
warning: src/c/mshabal_128.c:317:13: warning: unused parameter ‘ub0’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:              ^~~
warning: src/c/mshabal_128.c:317:27: warning: unused parameter ‘ub1’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                            ^~~
warning: src/c/mshabal_128.c:317:41: warning: unused parameter ‘ub2’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                                          ^~~
warning: src/c/mshabal_128.c:317:55: warning: unused parameter ‘ub3’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                                                        ^~~
warning: src/c/mshabal_128.c:317:69: warning: unused parameter ‘n’ [-Wunused-parameter]
warning:     unsigned ub0, unsigned ub1, unsigned ub2, unsigned ub3, unsigned n,
warning:                                                                      ^
warning: src/c/mshabal_128.c: In function ‘simd128_mshabal_openclose_fast’:
warning: src/c/mshabal_128.c:650:14: warning: unused parameter ‘n’ [-Wunused-parameter]
warning:      unsigned n)
warning:               ^
warning: src/c/shabal_sse2.c: In function ‘find_best_deadline_avx’:
warning: src/c/shabal_sse2.c:27:35: warning: unused parameter ‘scoops’ [-Wunused-parameter]
warning:  void find_best_deadline_avx(char *scoops, uint64_t nonce_count, char *gensig, uint64_t *best_deadline, uint64_t *best_offset) {}
warning:                                    ^~~~~~
warning: src/c/shabal_sse2.c:27:52: warning: unused parameter ‘nonce_count’ [-Wunused-parameter]
warning:  void find_best_deadline_avx(char *scoops, uint64_t nonce_count, char *gensig, uint64_t *best_deadline, uint64_t *best_offset) {}
warning:                                                     ^~~~~~~~~~~
warning: src/c/shabal_sse2.c:27:71: warning: unused parameter ‘gensig’ [-Wunused-parameter]
warning:  void find_best_deadline_avx(char *scoops, uint64_t nonce_count, char *gensig, uint64_t *best_deadline, uint64_t *best_offset) {}
warning:                                                                        ^~~~~~
warning: src/c/shabal_sse2.c:27:89: warning: unused parameter ‘best_deadline’ [-Wunused-parameter]
warning:  void find_best_deadline_avx(char *scoops, uint64_t nonce_count, char *gensig, uint64_t *best_deadline, uint64_t *best_offset) {}
warning:                                                                                          ^~~~~~~~~~~~~
warning: src/c/shabal_sse2.c:27:114: warning: unused parameter ‘best_offset’ [-Wunused-parameter]
warning:  void find_best_deadline_avx(char *scoops, uint64_t nonce_count, char *gensig, uint64_t *best_deadline, uint64_t *best_offset) {}
warning:                                                                                                                   ^~~~~~~~~~~
warning: src/c/shabal_sse2.c: In function ‘find_best_deadline_avx2’:
warning: src/c/shabal_sse2.c:28:36: warning: unused parameter ‘scoops’ [-Wunused-parameter]
warning:  void find_best_deadline_avx2(char *scoops, uint64_t nonce_count, char *gensig, uint64_t *best_deadline, uint64_t *best_offset) {}
warning:                                     ^~~~~~
warning: src/c/shabal_sse2.c:28:53: warning: unused parameter ‘nonce_count’ [-Wunused-parameter]
warning:  void find_best_deadline_avx2(char *scoops, uint64_t nonce_count, char *gensig, uint64_t *best_deadline, uint64_t *best_offset) {}
warning:                                                      ^~~~~~~~~~~
warning: src/c/shabal_sse2.c:28:72: warning: unused parameter ‘gensig’ [-Wunused-parameter]
warning:  void find_best_deadline_avx2(char *scoops, uint64_t nonce_count, char *gensig, uint64_t *best_deadline, uint64_t *best_offset) {}
warning:                                                                         ^~~~~~
warning: src/c/shabal_sse2.c:28:90: warning: unused parameter ‘best_deadline’ [-Wunused-parameter]
warning:  void find_best_deadline_avx2(char *scoops, uint64_t nonce_count, char *gensig, uint64_t *best_deadline, uint64_t *best_offset) {}
warning:                                                                                           ^~~~~~~~~~~~~
warning: src/c/shabal_sse2.c:28:115: warning: unused parameter ‘best_offset’ [-Wunused-parameter]
warning:  void find_best_deadline_avx2(char *scoops, uint64_t nonce_count, char *gensig, uint64_t *best_deadline, uint64_t *best_offset) {}
warning:                                                                                                                    ^~~~~~~~~~~
   Compiling num-bigint v0.1.44
   Compiling chrono v0.4.5
   Compiling log v0.4.3
   Compiling serde_json v1.0.19
   Compiling serde_yaml v0.7.4
   Compiling serde_derive v1.0.65
   Compiling flate2 v1.0.2
   Compiling serde-value v0.5.2
   Compiling url v1.7.1
   Compiling num-rational v0.1.42
   Compiling mio v0.6.14
   Compiling tokio-io v0.1.6
   Compiling tokio-threadpool v0.1.5
   Compiling want v0.0.5
   Compiling num v0.1.42
   Compiling tokio-reactor v0.1.1
   Compiling h2 v0.1.10
   Compiling stopwatch v0.0.7
   Compiling log4rs v0.8.0
   Compiling tokio-udp v0.1.0
   Compiling tokio-tcp v0.1.0
   Compiling tokio-fs v0.1.0
   Compiling tokio v0.1.7
   Compiling tokio-core v0.1.17
   Compiling hyper v0.12.5
    Finished dev [unoptimized + debuginfo] target(s) in 4m 36s
     Running `target/debug/scavenger`
07:13:10 [INFO]  SIMD extensions: SSE2
07:13:10 [INFO]  valid plot file: 10282355196851764065_0_8
07:13:10 [INFO]  path=test_data, files=1, size=0 TiB
07:13:10 [INFO]  plot files loaded: total capacity=0 TiB
07:13:10 [INFO]  new block: height=91425, scoop=803
07:13:10 [INFO]  deadline found: nonce=5, deadline=2801135413
07:13:10 [INFO]  round finished: roundtime=3ms

```

**Comment by spebern** [comment]
Thanks everyone for debugging and patience :-)
